CREATE TABLE ALR_ITEM
(
    ITEM_ID             VARCHAR(64) PRIMARY KEY NOT NULL,
    ITEM_NAME           VARCHAR(32),
    ITEM_TYPE           VARCHAR(32),
    ITEM_DESCRIPTION    VARCHAR(256),
    ITEM_VALUE          VARCHAR(64),
    ITEM_DAMAGE         VARCHAR(64),
    ITEM_PROTECTION     VARCHAR(64),
    ITEM_STAT_COURAGE   VARCHAR(64),
    ITEM_STAT_DEXTERITY VARCHAR(64),
    ITEM_STAT_WISDOM    VARCHAR(64),
    ITEM_STAT_HEALTH    VARCHAR(64),
    ITEM_STAT_MANA      VARCHAR(64),
);